# Generated by Django 5.1.1 on 2024-10-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinquiry',
            name='subject',
            field=models.TextField(),
        ),
    ]
