# Generated by Django 5.1.1 on 2024-10-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='emp_id',
            field=models.CharField(max_length=10),
        ),
    ]
