# Generated by Django 5.1.1 on 2024-10-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='date_created',
            field=models.DateField(),
        ),
    ]
