# Generated by Django 5.1.1 on 2024-10-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_newsarticle_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(blank=True, choices=[('sports', 'Sports'), ('agriculture', 'Agriculture'), ('technology', 'Technology'), ('health', 'Health'), ('education', 'Education')], default='', max_length=50, null=True),
        ),
    ]
